### ISSUE TITLE
Error when importing Sample App package file

### ISSUE THREAD

**Issue by mwarger** [dreamfactorysoftware/reactjs-sdk#2]
I'm trying to import the sample for ReactJS in dreamfactory and am getting the following error.

```
file_put_contents(C:\Bitnami\dreamfactory-2.5.0-1\apps\dreamfactory\htdocs\storage\app/AddressBookForReact/add_reactjs/node_modules/react-modal-bootstrap/node_modules/radium/node_modules/babel/node_modules/babel-core/lib/transformation/helpers/build-binary-assignment-operator-transformer.js): failed to open stream: Invalid argument
```

I am able to import other packages (like Angular or Ionic) without issues.  Please advise.

**Comment by mwarger** [comment]
This was resolved when ran on a linux machine.  Maybe a path issue with windows?

**Comment by campbellgreen** [comment]
Yes, the path is too long for windows to handle unless you are using windows 10 or server 2016 with NTFS long paths enabled. I have logged a new ticket regarding this issue. BTW - works with OSX also.
